char midi_init( char port );
inline int midi_encode_14bit( char fine, char coarse );
void midi_decode_14bit( int n, char *out );
void midi_send_control_change( char channel, char control, char value );
void midi_send_14bit_control_change( char channel, char control_coarse, char control_fine, int value );
void midi_send_note_on( char channel, char note, char velocity );
void midi_send_note_off( char channel, char note, char velocity );
void midi_send_after_touch( char channel, char note, char pressure );
void midi_send_program_change( char channel, char program );
void midi_send_channel_pressure( char channel, char pressure );
void midi_send_pitch_wheel( char channel, char pitch );
void midi_send_system_exclusive( char id, char * data, char data_size ); 
void midi_send_gm_system_enable( char channel );
void midi_send_gm_system_disable( char channel );
void midi_send_master_volume( char channel, unsigned int volume );
void midi_send_quarter_frame( char time_code );
void midi_send_song_position( int beat );
void midi_send_song_select( char song );
void midi_send_tune_request();
void midi_send_clock();
void midi_send_start();
void midi_send_continue();
void midi_send_stop();
void midi_send_active_sense();
void midi_send_reset();
char receive( int timeout, char timer_id, char ** out );
void midi_send_all_notes_off( char channel );
void midi_send_all_sound_off( char channel );
void midi_send_all_controllers_off( char channel );
void midi_send_mono_operation( char channel );
void midi_send_poly_operation( char channel );
